### ISSUE TITLE
Game booting error

### ISSUE THREAD

**Issue by Niconoko** [domanhthang2110/efiscompat#2]
![image](https://github.com/user-attachments/assets/3d22a5e2-b0a8-4dfb-ac67-7dc2d3256725)
[latest.log](https://github.com/user-attachments/files/17392316/latest.log)
[crash-2024-10-16_15.50.08-fml.txt](https://github.com/user-attachments/files/17392735/crash-2024-10-16_15.50.08-fml.txt)
This showed up after updated to v2.1.0
Me using Epic Fight v20.7.4 as it still work with the previous EF & ISS v2.0.1 Beta, and seem to show up the same with higher version of Epic FIght (Last used v20.9.4)

**Comment by domanhthang2110** [comment]
Please use the updated version on Curseforge, I haven't updated the release in Github for a while

**Comment by Niconoko** [comment]
It's fixed now, seem like me have to update other addon for EF too, cheers (´ - ω -｀)
