### ISSUE TITLE
Visual incompatibility with Ice and Fire Spellbooks

### ISSUE THREAD

**Issue by Verethragna8373** [domanhthang2110/efiscompat#4]
I was Just playing around in creative and i noticed that the staffs from the Ice and fire Spellbooks addon don't have the staff animation in 1.20.1, I am guessing this might be a bug but just wanted to let you know.

mods needed to replicate (file names/versions and the name of the mod on curseforge):
- epicfight-forge-20.9.5-1.20.1 (Epic Fight)
- caelus-forge-3.2.0+1.20.1 (Caelus API (Forge/NeoForge))
- citadel-2.6.0-1.20.1 (citadel)
- curios-forge-5.11.0+1.20.1 (curios API (Forge/NeoForge)))
- efiscompat-2.1.8 (Epic Fight x Iron's Spells Animation Fix)
- geckolib-forge-1.20.1-4.4.9 (GeckoLib)
- iceandfire-2.1.13-1.20.1-beta-5 (Ice and Fire: Dragons)
- ice_and_fire_spellbooks-2.3.1-1.20.1 (Ice and Fire: Spellbooks)
- irons_spellbooks-1.20.1-3.4.0.4 (Iron's Spells 'n Spellbooks)
- player-animation-lib-forge-1.0.2-rc1+1.20 (playerAnimator)

The steps to replicate:
- Create a new world (preferably in creative)
- Obtain A spell book, any "Dragon Priest staff" (Glacial, Infernal, Thunderous, or the default one) and any spell
- Attach the spell to the spell book and cast by right clicking with the "Dragon Priest Staff" in the main hand

I have also attached a recording as evidance if needed

https://github.com/user-attachments/assets/9d67b531-d914-42d7-b156-9cbe6ee0c448

**Comment by domanhthang2110** [comment]
This is adjustable via the config file, by default it only include staffs from the mod

**Comment by Verethragna8373** [comment]
Ok, I am just dense for not checking first, sorry about that
